// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu529yXU-EPDbKjQUgI5al_qJ3kQiMS8Q',
    appId: '1:452169253977:web:b96f74f534d61337ad9d48',
    messagingSenderId: '452169253977',
    projectId: 'resit-app-50f35',
    authDomain: 'resit-app-50f35.firebaseapp.com',
    storageBucket: 'resit-app-50f35.firebasestorage.app',
    measurementId: 'G-19ENYVRB2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB968NbGPyuB4cQFrBqfKbrLbdBhQdt7yc',
    appId: '1:452169253977:android:9672d99d6a3fd48fad9d48',
    messagingSenderId: '452169253977',
    projectId: 'resit-app-50f35',
    storageBucket: 'resit-app-50f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FNkHzqRBqvHC9AGJTSZj3KtAau53Z1U',
    appId: '1:452169253977:ios:354f9b787a254142ad9d48',
    messagingSenderId: '452169253977',
    projectId: 'resit-app-50f35',
    storageBucket: 'resit-app-50f35.firebasestorage.app',
    iosBundleId: 'com.seungbeen.resit',
  );
}
